version: '3'
services:
  tomcat_asr_agent:
    image: tomcat_asr_agent:latest
    container_name: tomcat_asr_agent
    build:
      context: .
      dockerfile: Dockerfile.asist
    ports:
      - 8888:8888
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/google_application_credentials.json
    volumes:
      - $GOOGLE_APPLICATION_CREDENTIALS:/google_application_credentials.json
      - .:/asr
    entrypoint: [
      "./tomcat_asr_agent",
      "websockets",
      "--use_mqtt",
      "--ws_host", "0.0.0.0",
      "--ws_port", "8888",
      "--mqtt_host", "host.docker.internal"
    ]
