version: '3'
services:
  tomcat_asr_agent:
    image: tomcat_asr_agent:latest
    container_name: tomcat_asr_agent
    build:
      context: ./asr
      dockerfile: Dockerfile.asist
    ports:
      - 8888:8888
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/google_application_credentials.json
    volumes:
      - $GOOGLE_APPLICATION_CREDENTIALS:/google_application_credentials.json
      - ./asr:/asr
  webmic:
    image: webmic:latest
    container_name: webmic
    build: ./webmic
    ports:
      - 8000:8000
